name: Run Image Generation Flask App

on:
  workflow_dispatch:
    inputs:
      titles:
        description: 'Titles for the podcast cover'
        required: true
      episode_id:
        description: 'Episode ID for the podcast cover'
        required: true

jobs:
  run_flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask App
        env:
          TITLES: ${{ github.event.inputs.titles }}
          EPISODE_ID: ${{ github.event.inputs.episode_id }}
        run: |
          echo "Running Flask App with Titles: $TITLES and Episode ID: $EPISODE_ID"
          python app.py  # Ensure your app.py is configured to read these environment variables
